export const {
  NEXT_PUBLIC_URL,
  NEXT_PUBLIC_HEADLESS_ID_CLIENT,
  NEXT_PUBLIC_HEADLESS_ID_STORE,
  NEXT_PUBLIC_ALL_PRODUCTS_ID,
  NEXT_PUBLIC_BEST_SELLERS_ID,
  NEXT_PUBLIC_ACCESORY_ID,
  NEXT_PUBLIC_NEW_COLLECTION_ID,
  NEXT_PUBLIC_OFFERS_ID,
} = process.env;
